This fixes SF bug #3272324
When OpenCryptoki is present, tpm-tools 1.3.5 fails to link with the gold linker. libtpm_pkcs11.a fails to link:
tpm-tools-1.3.1: /usr/libexec/gcc/i686-pc-linux-gnu/ld: ../../lib/.libs/libtpm_pkcs11.a(tpm_pkcs11.o): in function closeToken:tpm_pkcs11.c:287: error: undefined reference to 'dlclose'
(...)

The problem is that gold requires all libraries used to be explicitly specified on the command line.

Signed-off-by: Rajiv Andrade <srajiv@linux.vnet.ibm.com>